config/routes.rb
Rails.application.routes.draw do
  get "/root_recommendations", to: 'book_recommendations#by_teacher'

  resources :finished_books
  resources :book_recommendations do
    resources :comments
  end
  root to: 'welcome#index'
end

app/models/book_recommendation.rb
class BookRecommendation
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :title, :type => String, required: true
  field :author, :type => String, required: true
  field :student, :type => String, required: true
  field :description, :type => Text, required: false
  field :by_teacher, :type => Boolean

  has_many :comments
end

app/models/comment.rb
class Comment
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :student, :type => String, required: true
  field :body, :type => Text, required: true

  belongs_to :book_recommendation
end

app/models/finished_book.rb
class FinishedBook
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :title, :type => String, required: true
  field :author, :type => String, required: true
  field :student, :type => String, required: true
  field :central_idea, :type => Text, required: true
  field :genre, :type => String
end

app/models/user.rb
class User
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps
  include Clearance::User

  field :email, :type => String, required: true
  field :encrypted_password, :type => String, max_length: 128
  field :confirmation_token, :type => String, max_length: 128
  field :remember_token, :type => String, max_length: 128
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_recommendations_controller.rb
class BookRecommendationsController < ApplicationController
  before_action :set_book_recommendation, only: [:show, :destroy]

  def index
    @book_recommendations = BookRecommendation.where(by_teacher: false)
  end

  def new
    @book_recommendation = BookRecommendation.new
    if current_user
      @book_recommendation.student = "Mrs. Root"
      @book_recommendation.by_teacher = true
    end
  end

  def show
    if @book_recommendation.by_teacher?
      @book_recommendations = BookRecommendation.where(by_teacher: true)
    else
      @book_recommendations = BookRecommendation.where(by_teacher: false)
    end
  end

  def create
    @book_recommendation = BookRecommendation.new(book_recommendation_params)

    if current_user
      @book_recommendation.by_teacher = params[:book_recommendation][:by_teacher]
    else
      @book_recommendation.by_teacher = false
    end

    if @book_recommendation.save
      flash[:success] = "Recommendation successfully created."
      redirect_to book_recommendations_path
    else
      render :new
    end
  end

  def destroy
    if current_user
      @book_recommendation.destroy
      flash[:success] = "Book recommendation was successfully destroyed."
    else
      flash[:error] = "You're not allowed to remove recommendations."
    end

    redirect_to book_recommendations_path
  end

  def by_teacher
    @book_recommendations = BookRecommendation.where(by_teacher: true)
  end

  private

    def set_book_recommendation
      @book_recommendation = BookRecommendation.eager_load(:comments).find(params[:id])
    end

    def book_recommendation_params
      params.require(:book_recommendation).permit(:title, :author, :student, :description)
    end

end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  before_filter :redirect_signed_in_users, only: [:create, :new]
  skip_before_filter :require_login, only: [:create, :new]
  skip_before_filter :authorize, only: [:create, :new]

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    puts '*'*100
    puts params.inspect
    puts user_params.inspect
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    ::User.new(
      email: email,
      password: password
    )
  end

  def user_params
    params[:user] || Hash.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @book_recommendation = BookRecommendation.find(params[:book_recommendation_id])
    @comment = Comment.new(book_recommendation: @book_recommendation)
  end

  def create
    @book_recommendation = BookRecommendation.find(params[:book_recommendation_id])
    @comment = Comment.new(comment_params)

    if @comment.save
      flash[:success] = "Comment successfully saved."
      redirect_to book_recommendation_path(@book_recommendation)
    else
      render :new
    end
  end

  private

    def comment_params
      params.permit(:student, :body, :book_recommendation_id)
    end
end

app/controllers/finished_books_controller.rb
class FinishedBooksController < ApplicationController
  before_action :set_finished_book, only: [:show, :edit, :update, :destroy]

  def index
    @finished_books = FinishedBook.all
  end

  def show
  end

  def new
    @finished_book = FinishedBook.new
  end

  def edit
    if !current_user
      flash[:error] = "You're not allowed to edit finished books."
      redirect_to finished_books_path
    end
  end

  def create
    @finished_book = FinishedBook.new(finished_book_params)

    if @finished_book.save
      flash[:success] = 'Finished book was successfully created.'
      redirect_to finished_books_path
    else
      render :new
    end
  end

  def update
    if @finished_book.update(finished_book_params)
      redirect_to finished_books_path, notice: 'Finished book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if current_user
      @finished_book.destroy
      flash[:success] = 'Finished book was successfully destroyed.'
    else
      flash[:error] = "You're not allowed to remove finished books."
    end

    redirect_to finished_books_path
  end

  private

    def set_finished_book
      @finished_book = FinishedBook.find(params[:id])
    end

    def finished_book_params
      params.require(:finished_book).permit(:title, :author, :student, :central_idea, :genre)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

end

app/helpers/finished_books_helper.rb
module FinishedBooksHelper
end

app/views/book_recommendations/_form.html.erb
<%= bootstrap_form_for(@book_recommendation, label_errors: true) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  
  <%= f.text_field :student, class: "form-control", placeholder: "First name", label: "First name" %>

  <%= f.text_field :title, class: "form-control", placeholder: "Book title" %>

  <%= f.text_field :author, class: "form-control", placeholder: "Book author" %>

  <%= f.text_area :description, class: "form-control", rows: "5", label: "I would recommend this book because..." %>

  <% if current_user %>
    <%= f.check_box :by_teacher %>
  <% end %>
    
  <%= f.submit (@book_recommendation.id ? "Save" : "Add"), class: "btn btn-primary" %>
  <%= link_to 'Cancel', book_recommendations_path, class: "pull-right btn btn-danger" %>

<% end %>

app/views/book_recommendations/by_teacher.html.erb
<h1>Recommendations by Mrs. Root</h1>

<% if current_user %>
  <%= link_to 'I want to recommend a book', new_book_recommendation_path, class: "pull-left btn btn-primary" %>
<% end %>
<br>
<br>

<div class="col-md-4" style="padding-left: 0;">
  <div class="list-group">
    <% @book_recommendations.each do |rec| %>
      <%= link_to book_recommendation_path(rec) + "?by_teacher=true", class: "list-group-item #{@book_recommendation && rec.id == @book_recommendation.id ? 'active' : ''}" do %>
        <h4 class="list-group-item-heading">
          <%= rec.student.titleize %>
        </h4>

        <p class="list-group-item-text">
          <%= rec.title.titleize %> by  <%= rec.author.titleize %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/book_recommendations/index.html.erb
<%= link_to 'I want to recommend a book', new_book_recommendation_path, class: "pull-left btn btn-primary" %>

<br>
<br>

<div class="col-md-4" style="padding-left: 0;">
  <div class="list-group">
    <% @book_recommendations.each do |rec| %>
      <%= link_to rec, class: "list-group-item" do %>
        <h4 class="list-group-item-heading">
          <%= rec.student.titleize %>
        </h4>

        <p class="list-group-item-text">
          <%= rec.title.titleize %> by  <%= rec.author.titleize %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/book_recommendations/new.html.erb
<h1>Recommend a book</h1>

<%= render 'form' %>

app/views/book_recommendations/show.html.erb
<%= link_to 'I want to recommend a book', new_book_recommendation_path, class: "pull-left btn btn-primary" %>

<%= link_to "Comment on this recommendation", new_book_recommendation_comment_path(@book_recommendation), class: "btn btn-primary pull-right" %>

<br>
<br>

<div class="col-md-4" style="padding-left: 0;">
  <div class="list-group">
    <% @book_recommendations.each do |rec| %>
      <%= link_to rec, class: "list-group-item #{@book_recommendation && rec.id == @book_recommendation.id ? 'active' : ''}" do %>
        <h4 class="list-group-item-heading">
          <%= rec.student.titleize %>
        </h4>

        <p class="list-group-item-text">
          <%= rec.title.titleize %> by  <%= rec.author.titleize %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

<div class="col-md-8" style="padding-right: 0;">
  <h4 style="margin-top: 0;">I would recommend this book because...</h4>
  <p><%= @book_recommendation.description %></p>
  <br>

  <% @book_recommendation.comments.each do |comment| %>
    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <h4>
          <%= comment.student.titleize %>
          <div class="pull-right">
            <%= comment.created_at.strftime("%x") %>
          </div>
        </h4>
      </div>

      <div class="panel-body"><%= comment.body %></div>
    </div>
  <% end %>

  <% if @book_recommendation.comments.empty? %>
    <p>No comments yet</p>
  <% end %>
</div>

app/views/comments/new.html.erb
<h1>Add comment</h1>

<%= bootstrap_form_tag(url: "/book_recommendations/#{@book_recommendation.id}/comments", label_errors: true) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>

  <%= f.text_field :student, class: "form-control", placeholder: "First name", label: "First name" %>

  <%= f.text_area :body, class: "form-control", placeholder: "Comment", label: "Comment" %>

  <%= f.submit "Add Comment", class: "btn btn-primary" %>

<% end %>

app/views/finished_books/_form.html.erb
<%= bootstrap_form_for(@finished_book, label_errors: true) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  
  <%= f.text_field :student, class: "form-control", placeholder: "First name", label: "First name" %>

  <%= f.text_field :title, class: "form-control", placeholder: "Book title" %>

  <%= f.text_field :author, class: "form-control", placeholder: "Book author" %>

  <%= f.text_field :genre, class: "form-control", placeholder: "Informational or literature" %>

  <%= f.text_area :central_idea, class: "form-control", rows: "5", label: "Central idea/Overarching story line" %>
    
  <%= f.submit (@finished_book.id ? "Save" : "Add"), class: "btn btn-primary" %>
  <%= link_to 'Cancel', finished_books_path, class: "btn btn-danger pull-right" %>

<% end %>

app/views/finished_books/edit.html.erb
<h1>Edit Finished Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @finished_book %> |
<%= link_to 'Back', finished_books_path %>

app/views/finished_books/index.html.erb
<h1></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Central idea/overarching story line</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finished_books.each do |finished_book| %>
      <tr>
        <td><%= finished_book.student.titleize %></td>
        <td><%= finished_book.title.titleize %></td>
        <td><%= finished_book.author.titleize %></td>
        <td><%= finished_book.genre %></td>
        <td><%= truncate(finished_book.central_idea, length: 100) %></td>
        <td><%= link_to 'View', finished_book %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_finished_book_path(finished_book) %></td>
          <td><%= link_to 'Destroy', finished_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'I finished a book', new_finished_book_path, class: "btn btn-primary" %>

app/views/finished_books/new.html.erb
<h1>Add a Book I Finished</h1>

<%= render 'form' %>

app/views/finished_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @finished_book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @finished_book.author %>
</p>

<p>
  <strong>Student:</strong>
  <%= @finished_book.student %>
</p>

<p>
  <strong>Central idea:</strong>
  <%= @finished_book.central_idea %>
</p>

<% if current_user %>
  <%= link_to 'Edit', edit_finished_book_path(@finished_book) %> |
<% end %>
<%= link_to 'Back', finished_books_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Summer Reading", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'finished_books' %>">
          <%= link_to "Books That Have Been Read", finished_books_path %>
        </li>

        <li class="<%= 'active' if params[:controller] == 'book_recommendations' && controller.action_name != 'by_teacher' && !params[:by_teacher] %>">
          <%= link_to "Book Recommendations", book_recommendations_path %></li>
        </li>

        <li class="<%= 'active' if params[:controller] == 'book_recommendations' && params[:by_teacher] %>">
          <%= link_to "Recommendations From Mrs. Root", root_recommendations_path + "?by_teacher=true" %>
        </li>
      </ul>

      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" href="#">
              <%= current_user.email %>
              <span class="caret"></span>
            </a>

            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% end %>

    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mrs. Root's Class</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>

    <div class="container">
      <%= flash_messages %>

      <%= yield %>
    </div>

  </body>

</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h3 class="text-center">Welcome to Mrs. Root's Class</h3>

  <%= link_to "I finished a book!", new_finished_book_path, class: "btn btn-success btn-lg" %>

  <%= link_to "I want to recommend a book!", new_book_recommendation_path, class: "btn btn-success btn-lg" %>
</div>